### ISSUE TITLE
Reconnect для streaming-клиента не работает из-за закрытой сессии

### ISSUE THREAD

**Issue by andrewshkovskii** [daxartio/tinvest#106]
Сервер ws иногда рвет соединения по одной ему известной причине(Исключение `EofStream` пораждает `WSMsgType.CLOSED` и из итератора кидается `StopAsyncIteration`).
В итоге здесь мы выходим из цикла 
https://github.com/daxartio/tinvest/blob/466aa4615c559dd75ddf4e8c40fc7667c8d51d65/tinvest/streaming.py#L133
Вызывается `cleanup` https://github.com/daxartio/tinvest/blob/466aa4615c559dd75ddf4e8c40fc7667c8d51d65/tinvest/streaming.py#L154 где закрывается сессия. Что приводит к ошибке при попытке повторного соединения https://github.com/daxartio/tinvest/blob/466aa4615c559dd75ddf4e8c40fc7667c8d51d65/tinvest/streaming.py#L108
и реконнекта не происходит.

**Comment by daxartio** [comment]
Удалил 

```python
await self._cleanup(api)
```
Fix version 2.1.1

**Comment by andrewshkovskii** [comment]
@daxartio Спасибо за фикс.
Но теперь, кажется, есть новый баг:

Коллбеки для события `ServiceEventName.startup` будут вызываться каждый раз при попытке соединения(реконнекта). Но коллбеки для `cleanup` события не будут вызыватся в случае реконнекта. Таким образом , если есть коллбек на `ServiceEventName.startup` и там вызывается, например, подписка на свечи -- то она будет вызываться каждый, порождая таким образом множество одинаковых подписок на событие по свече

**Comment by daxartio** [comment]
cleanup будет вызываться только при правильной работе, при `asyncio.CancelledError`. Если у нас отвалился коннект, то не смысла отписываться от свеч. Подписки идемпотенты, то есть подписавшись два раза, будут приходить данные только один, кроме момента подписки.

**Comment by andrewshkovskii** [comment]
@daxartio Спасибо за ответ.
Я не нашел идемпотентности колбека на событие подписки. Можно попросить указать на это в коде? Спасибо :)

**Comment by daxartio** [comment]
Я спросил у ребят из openapi про подписки

**Comment by andrewshkovskii** [comment]
Ок, я понял. Я ошибался в понимании как подписка на событие из сокета работает.
Спасибо!
