### ISSUE TITLE
Пустые свечи, за короткое время

### ISSUE THREAD

**Issue by trackname01** [daxartio/tinvest#108]
Здравствуйте, ваша библиотека правда полезная. Но у меня возникла проблема, когда я получаю свечи за час, или за 30 минут, они приходят пустые.  За большое время - всё работает. Заранее спасибо за помощь!

**Comment by daxartio** [comment]
Здравствуйте. С этим вопросом надо в онсовной репозиторий OpenAPI. Предполагаю, что интервал указан не тот.

**Comment by trackname01** [comment]
Хорошо, скоро этим займусь :)

**Comment by virus-sudo** [comment]
> > Хорошо, скоро этим займусь :)
> 
> Добрый день! Вы, случаем, не решили эту проблему? У нас тут, в будущем, все те же траблы :)

Я решил, проблема была в часовом поясе, я передавал время, не в том часовом поясе, в котором надо.
