### ISSUE TITLE
Добавить обработку исключения RuntimeError: Session is closed в пример Streaming

### ISSUE THREAD

**Issue by recoshet** [daxartio/tinvest#117]
Если запустить код из примера Streaming, то через некоторое время он вывалится с ошибкой:
```
  File "...\venv\lib\site-packages\aiohttp\client.py", line 357, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed
```
Возможно такая конструкция исправит положение:
```
async def main():
    while True:
        try:
            await tinvest.Streaming(TOKEN, state={"postgres": ...}).add_handlers(events).run()
        except RuntimeError:
            pass
        finally:
            pass
```
Если так, кину реквест

**Comment by daxartio** [comment]
Не стоит это класть в пример. Данная ошибка следствие неправильно работующего кода. Игнорить точно не стоит, asyncio много где кидает RuntimeError

**Comment by recoshet** [comment]
Заранее извиняюсь за прямолинейность) Получается пример написан не правильно, если он в чистом виде падает со временем?

**Comment by daxartio** [comment]
Если код падает, то надо все условия описать. Я запустил на 1000 акциях, проработав час, ничего не упало.
Напиши какая ОС, весь трейсбек, версию питона и какое окружение. Тут проблема что aiohttp закрывает сессию, надо разобраться почему. У них недавно было обновление, которое могло на это повлиять
