### ISSUE TITLE
market_candles_get() возвращает 'NoneType'

### ISSUE THREAD

**Issue by luxrost** [daxartio/tinvest#129]
Успешно получаем свечу из функции:

```
def candle_data (
    figi, 
    int1 = candle_resolution,
    from1 ='2020-11-09T15:00:00.131642+03:00',
    to1 = '2020-11-09T15:01:00.131642+03:00'
    ):
    response = market_api.market_candles_get(figi = ticker_figi, from_ = from1, to = to1, interval = int1)
    if response.status_code == 200:
        return print(response.parse_json())
    else:
        return print(response.parse_error())

response = candle_data(figi = ticker_figi)
```

При попытке загнать ответ в pandas получаю ошибку: 'NoneType' object is not subscriptable.

```df_candles = pd.DataFrame(response['payload'])```

Оказалось, что получаемый response неиндексируемый объект.
`print ('response type:', type(response))` даёт `response type: <class 'NoneType'>`.

Всё ли верно? Как можно его получать в виде индексируемого json?

**Comment by daxartio** [comment]
Так нельзя делать

```python
return print(response.parse_json())
```

```python
return response.parse_json()
```
