### ISSUE TITLE
Отрицательные остатки в портфеле

### ISSUE THREAD

**Issue by luxrost** [daxartio/tinvest#130]
При наличии отрицательных остатков денежных средств портфеле (плечо), `portfolio_get()` не возвращает рублёвую позицию (RUB).
Остатки USD и EUR (в тч наличие плеча) возвращает корректно.

**Comment by daxartio** [comment]
С этим вопросом надо сюда https://github.com/TinkoffCreditSystems/invest-openapi/issues
