### ISSUE TITLE
теряется typehint для ResponseWrapper

### ISSUE THREAD

**Issue by ColCh** [daxartio/tinvest#137]
```python
sync_client = tinvest.SyncClient(token)
market_api = tinvest.MarketApi(sync_client)
response = market_api.market_search_by_ticker_get('FOOBAR') # должен быть ResponseWrapper
```

![image](https://user-images.githubusercontent.com/599439/100795220-c188b000-342f-11eb-80e4-9699070ed3db.png)

VScode, pylance

по F12 вижу такое

```python
    def market_search_by_ticker_get(self, ticker: str, **kwargs: Any) -> Any:
        """GET /market/search/by-ticker"""
        kwargs.setdefault('params', {})
        params = kwargs['params']
        params.setdefault('ticker', ticker)
        return self.client.request(
            'GET',
            '/market/search/by-ticker',
            response_model=MarketInstrumentListResponse,
            **kwargs,
        )
```

то есть, реально Any возвращает.

в исходниках такое

https://github.com/daxartio/tinvest/blob/bf10adae05347e8f15b07a673046517e85f243d4/tinvest/apis.py#L312

это специально так сделано?

**Comment by ColCh** [comment]
и для parse_json тоже модель теряется, приходится кастить

```python
    response = cast(tinvest.sync_client.ResponseWrapper, open_api.market.market_search_by_ticker_get(ticker))
    data = cast(tinvest.MarketInstrumentListResponse, response.parse_json())
```

дисклеймер: я пока новичок в питоне, и с типами особо не разбирался. если типы не позволяют докидывать возвращаемые значения, прошу закрыть ишью :)

**Comment by daxartio** [comment]
Есть такая проблема, в будущем скорее всего сделаю отдельно синхронные и асинхронные методы. Сейчас всё зависит от передаваемого клиента `SyncClient` и `AsyncClient`.
