### ISSUE TITLE
New Version 3.0

### ISSUE THREAD

**Issue by daxartio** [daxartio/tinvest#139]
Всем привет!

Скоро выложу новую версию SDK. Предварительно выкладываю issue, если у кого возникнут вопросы, предложения.

Большой упор был сделан на type hinting. Код стал больше питонячим (простым).

<details>
<summary>Примеры</summary>

### Streaming

Предоставляет асинхронный интерфейс.

> При сетевых сбоях будет произведена попытка переподключения.

```python
import asyncio
import tinvest as ti


async def main():
    async with ti.Streaming('TOKEN') as streaming:
        async for candle in streaming.get_candles('BBG0013HGFT4', '1min', 'request_id'):
            print(candle)
            break

        async for orderbook in streaming.get_orderbooks('BBG0013HGFT4', 5):
            print(orderbook)
            break

        async for instrument in streaming.get_instruments_info('BBG0013HGFT4'):
            print(instrument)
            break

        async for error in streaming.get_errors('request_id'):
            print(error)
            break


asyncio.run(main())
```

### Синхронный REST API Client

Для выполнения синхронных http запросов используется библиотека `requests`.

```python
import tinvest

TOKEN = "<TOKEN>"

client = tinvest.SyncClient(TOKEN)

response = client.get_portfolio()  # tinvest.PortfolioResponse
print(response.payload)
```

```python
# Handle error
...
client = tinvest.SyncClient(TOKEN)

try:
    response = client.get_operations("", "")
except tinvest.BadRequestError as e:
    print(e.response)  # tinvest.Error
```

### Асинхронный REST API Client

Для выполнения асинхронных http запросов используется библиотека `aiohttp`.
Клиенты имеют такой же интерфейс как в синхронной реализации, за исключением того,
что функции возвращают объект корутина.

```python
import asyncio
import tinvest

TOKEN = "<TOKEN>"


async def main():
    client = tinvest.AsyncClient(TOKEN)
    response = await client.get_portfolio()  # tinvest.PortfolioResponse
    print(response.payload)

    await client.close()

asyncio.run(main())
```

### Sandbox

Sandbox позволяет вам попробовать свои торговые стратегии, при этом не тратя реальные средства. Протокол взаимодействия полностью совпадает с Production окружением.

```python
client = tinvest.AsyncClient(SANDBOX_TOKEN, use_sandbox=True)
client = tinvest.SyncClient(SANDBOX_TOKEN, use_sandbox=True)
```
</details>

**Comment by daxartio** [comment]
Поменя streaming

```python
import asyncio
import tinvest as ti


async def main():
    async with ti.Streaming('TOKEN') as streaming:
        await streaming.candle.subscribe('BBG0013HGFT4', ti.CandleResolution.min1)
        await streaming.orderbook.subscribe('BBG0013HGFT4', 5)
        await streaming.instrument_info.subscribe('BBG0013HGFT4')
        async for event in streaming:
            print(event)


asyncio.run(main())
```

**Comment by daxartio** [comment]
Перевел все `float` в `Decimal`

**Comment by andrewshkovskii** [comment]
Ребята, если вы выпускаете такие ломающие изменения в мажорной версии -- пишите инструкцию по миграции или делайте бекпорт... Разбираться в исходниках как поломалась обратная совместимость -- занятие так себе.

**Comment by andrewshkovskii** [comment]
Раньше был пример как работать с отдельными событиями на streaming api, сейчас там только пример обработки какого-то события  -- ни тебе примера как с ошибками работать, ни примера с коллбеками на `cleanup`, `startup`, `error`. Как мигрировать существующий код прикажите? Написано, мол, более питонячий интерфейс -- а вышло совсем не так...

**Comment by daxartio** [comment]
Версия 2 будет поддерживаться. Можно использовать, если переезд сложный.
Возможно надо показать больше примеров использования, но казалось текущий интерфейс стал максимально простым. 
<details>
<summary>Вот пример:</summary>

```python
import asyncio

import tinvest


async def handle_reconnect():
    # Больше не поддерживается. Если есть потребность, можем добавить
    print('Reconnecting')


async def handle_candle(
    api: tinvest.Streaming,
    payload: tinvest.CandleStreaming
):
    print(payload)


async def handle_orderbook(
    api: tinvest.Streaming, payload: tinvest.OrderbookStreaming
):
    print(payload)


async def handle_instrument_info(
    api: tinvest.Streaming, payload: tinvest.InstrumentInfoStreaming
):
    print(payload)


async def handle_error(
    api: tinvest.Streaming, payload: tinvest.ErrorStreaming
):
    print(payload)


async def startup(api: tinvest.Streaming):
    await api.candle.subscribe("BBG0013HGFT4", tinvest.CandleResolution.min1)
    await api.orderbook.subscribe("BBG0013HGFT4", 5, "123ASD1123")
    await api.instrument_info.subscribe("BBG0013HGFT4")


async def cleanup(api: tinvest.Streaming):
    pass


async def main():
    HANDLER_BY_EVENT = {
        tinvest.Event.candle: handle_candle,
        tinvest.Event.orderbook: handle_orderbook,
        tinvest.Event.instrument_info: handle_instrument_info,
        tinvest.Event.error: handle_error,
    }
    async with tinvest.Streaming('TOKEN') as streaming:
        await startup(streaming)
        async for event in streaming:
            await HANDLER_BY_EVENT[event.event](streaming, event.payload)
        # атоматически будет отписан от всех событий
        await cleanup(streaming)


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        pass
```
</details>

**Comment by andrewshkovskii** [comment]
@daxartio Вот этот примером намного проще, спасибо. 👍 

В части rest-api да, стало приятнее(избавились от лишних сущностей-контейнеров для апи). Но переименование методов надо было сделать через deprecation warning, оставить на первых версиях бекпорт.

В части стриминга не очень очевидно было.
Не понятно же было какие типы ивентов и как их теперь обрабатывать, в исходниках сразу не найдешь.
С примером проще. Лучше его на главной разместить :)



> Версия 2 будет поддерживаться. 

Речь про бранч?

**Comment by daxartio** [comment]
Про deprecated сразу не подумал, надо было сделать, согласен. 

Добавил streaming в [examples/streaming_with_handlers.py](https://github.com/daxartio/tinvest/blob/61c211a2336aae7d5b6757bd9338a3458ef5bab0/examples/streaming_with_handlers.py)

Да, будет поддерживаться ветка, если надо пропатчить код, версии будут выложены на pypi как 2.x.x.
