### ISSUE TITLE
Не могу подобрать верные аргументы к функции

### ISSUE THREAD

**Issue by Mikhachill** [daxartio/tinvest#149]
Не могу подобрать верный тип аргументов в функции создания денег в API SandBox

![image](https://user-images.githubusercontent.com/33483457/102617939-fc3a5a00-414a-11eb-81f4-351564cdbd3c.png)

Ошибка в том что он не находит признака JSON в аргументе функции - попробовал различные типы и преобразование json.dumps() но это не помогло.
![image](https://user-images.githubusercontent.com/33483457/102617842-d614ba00-414a-11eb-88c2-b33fe9cb9408.png)

**Comment by daxartio** [comment]
Вот похожая проблема #64
