### ISSUE TITLE
Не нашел возможности разместить короткую позицию

### ISSUE THREAD

**Issue by AlksIDo** [daxartio/tinvest#156]
`client_sandbox.post_orders_market_order(figi=figi, body=tinvest.schemas.MarketOrderRequest(lots=amnt, operation=tinvest.schemas.OperationType('Buy')), broker_account_id='XXXXXXX')`
'Buy' и 'Sell' с отрицательными значениями не работают, в коде реализации для размещения таких позиций не нашел. Плохо смотрел или нет реализации?

**Comment by ddmrtc** [comment]
Короткая позиция sell и положительное число

Пн, 4 янв. 2021 г. в 20:55, AlksIDo <notifications@github.com>:

**Comment by AlksIDo** [comment]
На конкретном примере при отсутствии данных бумаг в портфеле:
`client_sandbox.post_orders_market_order(figi='BBG000BTCH57', body=tinvest.schemas.MarketOrderRequest(lots=5, operation=tinvest.schemas.OperationType('Sell')), broker_account_id='XXXXXXX')`
Приводит к:
`UnexpectedError: 500 {"trackingId":"c941462d3a38f701","payload":{"message":"Cannot process request, not enough balance on security=BBG000BTCH57","code":"NOT_ENOUGH_BALANCE"},"status":"Error"}`
Пытается продать уже существующие позиции, даже при их нулевом балансе, а не создать короткую позицию

**Comment by daxartio** [comment]
Это сюда https://github.com/TinkoffCreditSystems/invest-openapi/

**Comment by ddmrtc** [comment]
Короткие позиции в песочнице не работают

Вт, 5 янв. 2021 г. в 23:12, Danil Akhtarov <notifications@github.com>:
