### ISSUE TITLE
Как корректно остановить streaming API?

### ISSUE THREAD

**Issue by stepochkin** [daxartio/tinvest#160]
У меня есть GUI (pyside2 обёртка QT) поток и поток asyncio, в котором запущен tinvest.Streaming.run.
Как мне из потока графического интерфейса (например по нажатию кнопки) остановить и корректно закрыть streaming API?

**Comment by daxartio** [comment]
Дам короткий ответ. Надо использовать `QSignal` и добавить callback функцию, в которой нужно вызвать метод `close` у `aiohttp.Session`.

```python
import asyncio
import aiohttp
import tinvest

async def main(qsignal):
    streaming = tinvest.Streaming(TOKEN, session=aiohttp.Session())
    def stop():
        loop = asyncio.get_running_loop()
        loop.run_until_complete(session.close())
    qsignal.connect(stop)
    await streaming.run()

...

qsignal.emit()
```
