### ISSUE TITLE
AttributeError: 'SyncClient' object has no attribute 'get_portfolio'

### ISSUE THREAD

**Issue by kolyadub** [daxartio/tinvest#197]
Здравствуйте,

Установив эту библиотеку, поробовал ваш синхронный пример на нескольких окружениях, но везде получаю ошибку с недоступностью 'get_portfolio'. Что может быть не так?

```
import tinvest

TOKEN = "<TOKEN>"

client = tinvest.SyncClient(TOKEN)

response = client.get_portfolio()  # tinvest.PortfolioResponse
print(response.payload)
```

**Comment by daxartio** [comment]
Здравствуйте

Какую версию вы используете?
`tinvest.__version__`

**Comment by kolyadub** [comment]
> Здравствуйте
> 
> Какую версию вы используете?
> `tinvest.__version__`

'2.3.3'

**Comment by daxartio** [comment]
Сейчас актуально 3.0
Попробуйте обновить версию.

**Comment by kolyadub** [comment]
Окей, проблема была в том, что окружения были на Python 3.7 и для него последняя версия 2.3.3. Не заметил плашки с версиями изначально.

**Comment by Romant1k** [comment]
не может установить новую версию
----- Установка "tinvest" -----
ERROR: Could not find a version that satisfies the requirement tinvest==3.0.5 (from versions: 1.0.7, 1.0.8, 1.0.9, 1.0.10, 1.0.11, 1.0.12, 1.0.13, 1.0.14, 1.0.15, 1.0.16, 1.0.17, 1.0.18, 1.0.19, 1.0.20, 1.0.21, 1.0.22, 1.0.23, 1.0.24, 2.0.0, 2.1.0, 2.1.1, 2.2.0, 2.3.0, 2.3.1, 2.3.2, 2.3.3)
ERROR: No matching distribution found for tinvest==3.0.5
----- Не удалось установить "tinvest". -----

**Comment by daxartio** [comment]
Требуется python 3.8 или выше
