### ISSUE TITLE
Доработать поддержку sandbox

### ISSUE THREAD

**Issue by wooloodya** [daxartio/tinvest#2]
В SandboxApi сейчас только 4 метода. По идее должны быть доступны все имеющиеся методы. Чтобы полностью разграничить рабочее окружение с токеном для sandbox.

**Comment by daxartio** [comment]
В документации пока описано только 4 метода

**Comment by wooloodya** [comment]
Остальные по факту также рабочие.

`curl -X GET "https://api-invest.tinkoff.ru/openapi/sandbox/market/search/by-ticker?ticker=AAPL" -H  "accept: application/json" -H  "Authorization: Bearer {TOKEN}"`

**Comment by daxartio** [comment]
Ок
