### ISSUE TITLE
WinError 10054

### ISSUE THREAD

**Issue by alyonka81** [daxartio/tinvest#217]
Добрый день.

Пыталась поставить рыночные заявки на покупку и выскочила ошибка:
`ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение`

При этом, днем ранее все нормально работало. С чем может быть связано?

**Comment by daxartio** [comment]
Добрый день. 
Такие запросы нужно повторять. Возможно были перезапущены сервера.
