### ISSUE TITLE
Примеры по Rest

### ISSUE THREAD

**Issue by felixrap** [daxartio/tinvest#25]
Добавьте, пожалуйста, примеры по использованию rest. Запросы истории и т.п

**Comment by daxartio** [comment]
В скором времени, добавлю документацию.
Будет доступна по этому адресу https://tinvest.readthedocs.io/ru/latest/

**Comment by felixrap** [comment]
Пишу по аналогии с тем, что есть на данный момент в примерах.

async def request():
    async with api.market_candles_get("BBG000B9XRY4", from_=curtime, to=curtime,
                                     interval=tinvest.CandleResolution.min1) as response:
        if response.status == 200:
            print(await response.parse_json())

получаю ответ
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001C355A751C8>

Почему это может быть?

**Comment by daxartio** [comment]
Aiohttp требует закрытие сессии при завершении, у них в документации про это написано. Я стараюсь такие вещи не обрабатывать.

**Comment by felixrap** [comment]
Если планируются ещё добавления, то хотелось бы видеть, как корутину распарсеную добавить в коллекцию с явными методами типа getHigh. getLow и т.п. Чтобы собрать пачку объектов, полученных с асинхрона

**Comment by daxartio** [comment]
Я если честно не понял о чём идёт речь. Можете написать ресурс, для которого нужен пример? Что значит "...корутину распарсеную"

**Comment by felixrap** [comment]
Запрашиваю историю за неделю в цикле. Не понял, как работать с объектами внутри. Например вытащить все полученные Low. Т.е мы получаем от тинькова ответы, распаршеваем их, а как дальше по свечке обратиться, например, какой у неё Low был

**Comment by daxartio** [comment]
```python
candles_response = await response.parse_json()
# CandlesResponse
candles_response.payload.candles[0].l
```

**Comment by felixrap** [comment]
наверное у меня проблема с pycharm. не видит он эти методы l,c,h и т.п. Не работает автоподсказка. Но если руками прописать, то работает ок.
