### ISSUE TITLE
tzinfo in str replace?

### ISSUE THREAD

**Issue by Kwentar** [daxartio/tinvest#262]
Hi, I am not sure, but it isn't look like good. Here is expected that `dt` is `str`, but `str.replace` doesn't have 'tzinfo' parameter. 
https://github.com/daxartio/tinvest/blob/01665b161cdbfffd51928bc7dd3363ab2d4a16f1/tinvest/utils.py#L57

Looks like here will be good `datetime.strptime` or [dateutil](https://pypi.org/project/python-dateutil/) package

**Comment by daxartio** [comment]
Hi, this functions gets str or datetime object. And "dt" is datetime. Standart python datetime object doesn't have of offset.

**Comment by daxartio** [comment]
I will be check tzinfo before replacing
