### ISSUE TITLE
Актуальность примеров

### ISSUE THREAD

**Issue by RailMan123** [daxartio/tinvest#266]
Не могли бы расписать актуальные примеры в описании клиентов(clients)? На данный момент, к примеру, у объекта client отсутствует метод get_portfolio(). Вместо этого есть лишь метод request(). На счет параметров этого метода также есть вопросы. С параметром method понятно(POST/GET), но что нужно для параметра path? Попытался вставить туда такой адрес https://api-invest.tinkoff.ru/openapi/sandbox/sandbox/register, но получил '_response': <Response [404]>, при вызове response.__dict__ (response - объект Response). Что вставить в параметр response_model тоже не разобрался. подставил туда tinvest.Empty, но не понял, что можно вставить туда вместо tinvest.Empty, сработает ли, если подставить туда "json"?

**Comment by daxartio** [comment]
Какая версия библиотеки?

**Comment by daxartio** [comment]
Есть пример https://github.com/daxartio/tinvest/blob/master/examples/portfolio_candles.py.
И этот пример работает.
Возможно используется старая версия либы.
