### ISSUE TITLE
Неправильный роут в библиотеке? 

### ISSUE THREAD

**Issue by teplinsky-maxim** [daxartio/tinvest#271]
Привет! Решил посмотреть на это API, но с самого начала пошли какие-то проблемы. Нет понятного примера по использованию синхронного клиента. Но все началось еще до этого. Пытаюсь получить аккаунт как сказано в #64, но мне говорят 404. 

```
def sandbox_register_post(
    request: Request[SandboxRegisterResponse],
    body: SandboxRegisterRequest,
) -> Response[SandboxRegisterResponse]:
    """
    POST /sandbox/register
    """
    kwargs: Any = {}
    kwargs.setdefault('data', body.json(by_alias=True))
    return request(
        'POST',
        '/sandbox/register',
        response_model=SandboxRegisterResponse,
        **kwargs,
    )
```
Это резолвится в https://api-invest.tinkoff.ru/openapi/sandbox/register.

В тоже время в API на Go URL такой: https://api-invest.tinkoff.ru/openapi/sandbox/sandbox/register, и там все работает. Исправил в либе путь на 
```
    return request(
        'POST',
        '/sandbox/sandbox/register',
        response_model=SandboxRegisterResponse,
        **kwargs,
    )
```
и заработало. В последней версии неправильные роуты или я неправильно использую библиотеку? До кучи еще задам вопрос, как все-таки получить портфель правильно? `client.get_portfolio()` ждет какой-то ID, но не ясно какой. В коде ниже ответ будет 500
```
import os

import tinvest as ti
from dotenv import load_dotenv

load_dotenv()

TOKEN = os.getenv("TOKEN")


def main():
    client = ti.SyncClient(TOKEN)
    account = client.register_sandbox_account(ti.SandboxRegisterRequest(broker_account_type=ti.BrokerAccountType.tinkoff))

    portfolio = client.get_portfolio(account.payload.broker_account_id) # 500
    print(portfolio)


if __name__ == '__main__':
    main()
```

**Comment by daxartio** [comment]
```python
client = ti.SyncClient(TOKEN, use_sandbox=True)
```
