### ISSUE TITLE
Установка tinvest 

### ISSUE THREAD

**Issue by Romant1k** [daxartio/tinvest#276]
Версия python 3.7

----- Установка "tinvest" -----
ERROR: Could not find a version that satisfies the requirement tinvest==3.0.5 (from versions: 1.0.7, 1.0.8, 1.0.9, 1.0.10, 1.0.11, 1.0.12, 1.0.13, 1.0.14, 1.0.15, 1.0.16, 1.0.17, 1.0.18, 1.0.19, 1.0.20, 1.0.21, 1.0.22, 1.0.23, 1.0.24, 2.0.0, 2.1.0, 2.1.1, 2.2.0, 2.3.0, 2.3.1, 2.3.2, 2.3.3)
ERROR: No matching distribution found for tinvest==3.0.5
----- Не удалось установить "tinvest". -----

**Comment by daxartio** [comment]
Требуется python 3.8 и выше
