### ISSUE TITLE
Неверный формат поля 'interval' в запросе

### ISSUE THREAD

**Issue by felixrap** [daxartio/tinvest#29]
Добрый день.

При запросе 
`async with api.market_candles_get(figi="BBG000B9XRY4", from_=pasttime,
                            to=curtime,interval=tinvest.CandleResolution.min1)`

получаю 
> {'message': "Неверный формат поля 'interval' в запросе", 'code': 'MALFORMED_QUERY_PARAMETER'} status='Error'

если поменять на _interval='1min'_, то всё ок.

**Comment by daxartio** [comment]
Понял, постараюсь на днях исправить

**Comment by daxartio** [comment]
Fix in v1.0.22
