### ISSUE TITLE
Ошибка RuntimeError: Event loop is closed в python3.8 на Windows

### ISSUE THREAD

**Issue by akudryav** [daxartio/tinvest#305]
На винде возникает ошибка RuntimeError: Event loop is closed
Для решения этого бага нужно добавить перед вызовом asyncio.run

if sys.version_info[0] == 3 and sys.version_info[1] >= 8 and sys.platform.startswith('win'):
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
Источник: encode/httpx#914

**Comment by daxartio** [comment]
Все так. У себя также делал. Можно вынести в ФАК в ридми файле. Можно закинуть ПР

**Comment by daxartio** [comment]
Я закрою проблему. Думаю решается на стороне клиента. Надо будет описать в FAQ
