### ISSUE TITLE
Номинал для облигаций.

### ISSUE THREAD

**Issue by viktorov-aa** [daxartio/tinvest#306]
В тинькофф апи у облигаций так же есть номинал(faceValue). Однако, в текущей модели данных библиотека его не отдает. Можно добавить?
Запрос: /market/bonds
Пример:
```
      {
        "figi": "BBG00QJ5M7P3",
        "ticker": "RU000A100W29",
        "isin": "RU000A100W29",
        "minPriceIncrement": 0.0334,
        "faceValue": 334,
        "lot": 1,
        "currency": "RUB",
        "name": "Роделен выпуск 2",
        "type": "Bond"
      }
```

PS
При этому тинькофф знает номинал не у всех облигаций.

**Comment by daxartio** [comment]
Для этого запроса в схеме нет этого поля 
![image](https://user-images.githubusercontent.com/11211587/143062987-095fc78e-5bf3-4bb0-b516-732430159eda.png)

Если в спеке добавят, я тоже добавлю поддержку

**Comment by viktorov-aa** [comment]
В спеке нет, а в результатах есть :(

**Comment by daxartio** [comment]
Напиши в основной репозиторий
