### ISSUE TITLE
tinvest postgresql

### ISSUE THREAD

**Issue by mardrake** [daxartio/tinvest#310]
Всём привет, 
Вопрос такой, как лучше организовать складирование в базу, на данный момент асинхронно тяну 2последние свечи хотя последняя динамична, а сори за 30 минут. Тяну за 2 дня, что бы в конце сессии попадала последняя свеча, между запросами делаю паузу, как писалось выше через await sleep и пишу в в базу через SQL alchemy, база одна имена таблиц тикеры, прошу подскажите, может есть лучше способ?

**Comment by daxartio** [comment]
Привет. Тебе тут не нужно использовать асинхронный клиент. Если ты используешь алхимию.

**Comment by daxartio** [comment]
В чем именно вопрос?

**Comment by mardrake** [comment]
Вопрос в том как лучше организовать складирование, более точно так сказать))

**Comment by mardrake** [comment]
> Привет. Тебе тут не нужно использовать асинхронный клиент. Если ты используешь алхимию.

То есть, ты считаешь что не нужно использовать асинхронный код, то есть синхронным через промежуток времени?

**Comment by daxartio** [comment]
Все так. Делай запросы и собирай данные синхронным клиентом. Асинхронный клиент нужен, если нужно одновременно много коннектов держать и соответственно делать одновременно несколько запросов, без использования потоков

**Comment by daxartio** [comment]
Складирую батчами, каждый запрос будет и так возвращать пачку данных
