### ISSUE TITLE
Реализация Метод получения списка фьючерсов

### ISSUE THREAD

**Issue by AndreyRzhaksinskiy** [daxartio/tinvest#313]
Возможно ли реализовать новые вызовы для просмотра списка фьючерсов?
https://github.com/Tinkoff/investAPI/blob/main/src/docs/contracts/instruments.proto

  //Метод получения списка фьючерсов.
  rpc Futures (InstrumentsRequest) returns (FuturesResponse);

**Comment by daxartio** [comment]
https://github.com/Tinkoff/invest-python

**Comment by daxartio** [comment]
Этот репозиторий работает только с API v1
