### ISSUE TITLE
Токен для чтения не подходит | 403

### ISSUE THREAD

**Issue by solesensei** [daxartio/tinvest#314]
Попытался использовать **токен для чтения**, так как мне нужно провести только аналитику портфеля 

![image](https://user-images.githubusercontent.com/24857057/150654701-602256ee-d30c-4225-a4c6-edad96965147.png)

```py
>>> client = tinvest.SyncClient(token)
>>> portfolio = client.get_portfolio()
tinvest.exceptions.UnexpectedError: 403 
```

С **токеном полного доступа** все ок.

Возможно не поддерживается `Tinkoff Invest API v.2`

**Comment by ddmrtc** [comment]
Токен для чтения работает только в api v2, эта библиотека работает по api v1

Сб, 22 янв. 2022 г. в 23:44, solesensei ***@***.***>:

**Comment by solesensei** [comment]
@ddmrtc спасибо
Есть ли в планах переход на api v2?

**Comment by daxartio** [comment]
https://github.com/Tinkoff/invest-python
