### ISSUE TITLE
Дайте пожалуйста пример get_market_candles

### ISSUE THREAD

**Issue by MixaSg** [daxartio/tinvest#315]
Добрый день!
Подскажите пожалуйста, чем кормить get_market_candles. Я уже весь истёрся. 

market = await client.get_market_candles('BBG000B9XRY4', now.strftime("%Y-%m-%d %H:%M:%S"), now.strftime("%Y-%m-%d %H:%M:%S"), '1min') - не работает, не могу понять, какие типы нужны, что только не пробовал - int, str и т.д.

Ошибка одна и та же:
  File "/home/mixa/anaconda3/envs/bender/lib/python3.10/site-packages/tinvest/clients.py", line 409, in get_market_candles
    return await market_candles_get(
  File "/home/mixa/anaconda3/envs/bender/lib/python3.10/site-packages/tinvest/apis.py", line 331, in market_candles_get
    params.setdefault('interval', interval.value)
AttributeError: 'str' object has no attribute 'value'

Спасибо.

**Comment by daxartio** [comment]
```python
market = await client.get_market_candles('BBG000B9XRY4', now, now, CandleResolution.min1)
```
