### ISSUE TITLE
Нет котировок по тикетам AGN и LSNG

### ISSUE THREAD

**Issue by truedmitri** [daxartio/tinvest#35]
Зачитываю пока минутные котировки по REST последовательно по всем бумагам. Есть несколько бумаг, по которым ничего не приходит, хотя в приложении Тинькофф инвестиции сделки по ним за этот период были.

Еще иногда бывает так, что по любым бумагам в ответ на marketApi.market_candles_get приходит пустой ответ, вместо json.

**Comment by pkosukhin** [comment]
По LSNG и LSNGP остановлены торги, идет реорганизация компаний.
