### ISSUE TITLE
Доработать асинхронный клиент

### ISSUE THREAD

**Issue by wooloodya** [daxartio/tinvest#4]
Зачем-то хорошо проработан синхронный клиент, асинхронный при этом существует в общем виде. Хотя по логике должно быть наоборот.
Предлагаю логику из синхронного клиента перенести в асинхронный. А от поддержки синхронного можно и отказаться.

**Comment by daxartio** [comment]
Асинхронный клиент также проработан как синхронный. Можно просто сделать замену  `PortfolioApi(AsyncClient('token'))` и использовать `async/await`

**Comment by wooloodya** [comment]
Ок, понял. В таком случае есть предложение избавиться от лишних абстракций. Из-за которых сейчас асинхронный клиент может работать только через `async with`:

```
    client = tinvest.AsyncClient(TOKEN)
    market_api = tinvest.MarketApi(client)
    async with market_api.market_stocks_get() as response:
        result = await response.parse_json()
```

Если избавиться от синхронного клиента (он ведь не нужен?) и упростить интерфейс остальных классов, то можно получить нечто подобное:


```
    api = tinvest.Api(TOKEN)
    market_stocks = await api.market_stocks_get()
```

**Comment by daxartio** [comment]
aiohttp использует контекстный менеджер (`async with`) тут я с этим ничего не поделаю. Сам синхронный код намного проще, легче писать тесты и я хочу сделать консольный клиент, там скорее всего с ним (синхронной реализациеё) будет правильней. Можно конечно использовать что-то вроде httpx, но он пока нестабильный.

**Comment by wooloodya** [comment]
Ладно, есть еще беда у клиента. Обработка ошибок в ResponseWrapper.
```
result = await response.parse_json()
```
Если сервер вернул ошибку, то мы не узнаем какую именно т.к. получим `validation_error` от сериаллизации в `response_model`

**Comment by wooloodya** [comment]
Предлагаю рейзить `ApiClientError` в случае 4хх ответа от сервера и `ApiServerError` в случае 5хх

**Comment by daxartio** [comment]
Обычно смотрят код ответа status_code

**Comment by wooloodya** [comment]
Ок, понял. Спасибо. Не увидел `__getattr__` сразу.

PS Там есть PR от меня. Будут комментарии, мнения, предложения? Это критичный фикс.
