### ISSUE TITLE
Ошибка загрузки свечи при проходе через новый год

### ISSUE THREAD

**Issue by felixrap** [daxartio/tinvest#41]
Добрый день!

Гружу минутные свечки. При проходе через НГ получаю: 

aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api-invest.tinkoff.ru/openapi/sandbox/market/candles?figi=BBG000B9XRY4&from=2015-12-31T16:53:18.493819%2B00:00&to=2016-01-01T16:53:18.493819%2B00:00&interval=1min')
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000016C27A5C588>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000016C27A6A128>, 358039.328)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000016C27A5C448>

Process finished with exit code 1

Как можно обработать?

**Comment by daxartio** [comment]
Токен от песочницы используется? Я повторил запрос проблем никаких не обнаружил.

**Comment by felixrap** [comment]
Да, токен был с песочницы.
Странно, сейчас делаю тоже самое, но ошибки нет. Может отваливалось что-то.
Закрою тогда задачу.
