### ISSUE TITLE
Регистрация клиента в Sandbox

### ISSUE THREAD

**Issue by felixrap** [daxartio/tinvest#64]
Добрый день. 
Функционал регистрации в песочнице рабочий? 
Пытаюсь зарегить новый токен, но получаю
_TypeError: sandbox_register_post() missing 1 required positional argument: 'body'_
если в body прописать SandboxRegisterRequest('Tinkoff'), то тоже не помогает.
Если не ошибаюсь, раньше оно работало именно так. 
Что-то изменилось на стороне Тинькова? В сваггере вроде тоже не пишут, что что-то передавать надо.

**Comment by daxartio** [comment]
```python
client.sandbox_register_post(SandboxRegisterRequest(broker_account_type=BrokerAccountType.tinkoff))
```
