### ISSUE TITLE
Лимиты запросов в синхронном REST API Client

### ISSUE THREAD

**Issue by MeCrazyJunkie** [daxartio/tinvest#67]
Хотелось бы иметь встроенную поддержку лимитов запросов Тинькофф апи https://tinkoffcreditsystems.github.io/invest-openapi/rest/

**Comment by daxartio** [comment]
Это следует обрабатывать на своей стороне. Обычно такие вещи решаются ретраями. Могу предложить библиотеку [tenacity](https://github.com/jd/tenacity).
Попробую сделать что-то похожее, чтобы можно было удобно использовать.
