### ISSUE TITLE
Обработка исключений в Streaming

### ISSUE THREAD

**Issue by wooloodya** [daxartio/tinvest#9]
Создаю новый issue т.к. не могу переоткрыть #3.

Там сейчас есть проблема с обработкой исключений. Например, если исключение возникнет в методе startup, то это вызовет вечный реконнект.

Я сделал pull request с лечением проблемы.

Предложения, мнения, пожелания?

**Comment by daxartio** [comment]
Стоит обработать конкретные исключения для реконнекта. Если всё обрабатывать, то это плохая практика

**Comment by daxartio** [comment]
Duplicate of #3

**Comment by daxartio** [comment]
Fix
